# SPDX-License-Identifier: GPL-2.0
ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
	dtbo-$(CONFIG_ARCH_SDM845) += \
		sdm845-cdp-overlay.dtbo \
		sdm845-mtp-overlay.dtbo \
		sdm845-qrd-overlay.dtbo \
		sdm845-4k-panel-mtp-overlay.dtbo \
		sdm845-4k-panel-cdp-overlay.dtbo \
		sdm845-4k-panel-qrd-overlay.dtbo \
		sdm845-v2-qvr-evt-overlay.dtbo \
		sdm845-v2-qvr-dvt-overlay.dtbo \
		sdm845-v2-cdp-overlay.dtbo \
		sdm845-v2-mtp-overlay.dtbo \
		sdm845-v2-qrd-overlay.dtbo \
		sdm845-v2-4k-panel-mtp-overlay.dtbo \
		sdm845-v2-4k-panel-cdp-overlay.dtbo \
		sdm845-v2-4k-panel-qrd-overlay.dtbo \
		sdm845-v2.1-cdp-overlay.dtbo \
		sdm845-v2.1-mtp-overlay.dtbo \
		sdm845-v2.1-qrd-overlay.dtbo \
		sdm845-v2.1-4k-panel-mtp-overlay.dtbo \
		sdm845-v2.1-4k-panel-cdp-overlay.dtbo \
		sdm845-v2.1-4k-panel-qrd-overlay.dtbo \
		sda845-cdp-overlay.dtbo \
		sda845-mtp-overlay.dtbo \
		sda845-qrd-overlay.dtbo \
		sda845-4k-panel-mtp-overlay.dtbo \
		sda845-4k-panel-cdp-overlay.dtbo \
		sda845-4k-panel-qrd-overlay.dtbo \
		sda845-v2-cdp-overlay.dtbo \
		sda845-v2-mtp-overlay.dtbo \
		sda845-v2-qrd-overlay.dtbo \
		sda845-v2-hdk-overlay.dtbo \
		sda845-v2-svr-overlay.dtbo \
		sda845-v2-4k-panel-mtp-overlay.dtbo \
		sda845-v2-4k-panel-cdp-overlay.dtbo \
		sda845-v2-4k-panel-qrd-overlay.dtbo \
		sda845-v2.1-cdp-overlay.dtbo \
		sda845-v2.1-mtp-overlay.dtbo \
		sda845-v2.1-qrd-overlay.dtbo \
		sda845-v2.1-svr-overlay.dtbo \
		sda845-v2.1-4k-panel-cdp-overlay.dtbo \
		sda845-v2.1-4k-panel-mtp-overlay.dtbo \
		sda845-v2.1-4k-panel-qrd-overlay.dtbo \
		sda845-v2.1-cdp-sdxpoorwills-overlay.dtbo \
		sda845-v2.1-mtp-sdxpoorwills-overlay.dtbo \
		sda845-v2-mtp-sdxpoorwills-overlay.dtbo \
		ZS620KL-overlay.dtbo

ZS620KL-overlay.dtbo-base := sdm845-v2.dtb
sdm845-cdp-overlay.dtbo-base := sdm845.dtb
sdm845-mtp-overlay.dtbo-base := sdm845.dtb
sdm845-qrd-overlay.dtbo-base := sdm845.dtb
sdm845-4k-panel-mtp-overlay.dtbo-base := sdm845.dtb
sdm845-4k-panel-cdp-overlay.dtbo-base := sdm845.dtb
sdm845-4k-panel-qrd-overlay.dtbo-base := sdm845.dtb
sdm845-v2-qvr-evt-overlay.dtbo-base := sdm845-v2.dtb
sdm845-v2-qvr-dvt-overlay.dtbo-base := sdm845-v2.dtb
sdm845-v2-cdp-overlay.dtbo-base := sdm845-v2.dtb
sdm845-v2-mtp-overlay.dtbo-base := sdm845-v2.dtb
sdm845-v2-qrd-overlay.dtbo-base := sdm845-v2.dtb
sdm845-v2-4k-panel-mtp-overlay.dtbo-base := sdm845-v2.dtb
sdm845-v2-4k-panel-cdp-overlay.dtbo-base := sdm845-v2.dtb
sdm845-v2-4k-panel-qrd-overlay.dtbo-base := sdm845-v2.dtb
sdm845-v2.1-cdp-overlay.dtbo-base := sdm845-v2.1.dtb
sdm845-v2.1-mtp-overlay.dtbo-base := sdm845-v2.1.dtb
sdm845-v2.1-qrd-overlay.dtbo-base := sdm845-v2.1.dtb
sdm845-v2.1-4k-panel-mtp-overlay.dtbo-base := sdm845-v2.1.dtb
sdm845-v2.1-4k-panel-cdp-overlay.dtbo-base := sdm845-v2.1.dtb
sdm845-v2.1-4k-panel-qrd-overlay.dtbo-base := sdm845-v2.1.dtb
sda845-cdp-overlay.dtbo-base := sda845.dtb
sda845-mtp-overlay.dtbo-base := sda845.dtb
sda845-qrd-overlay.dtbo-base := sda845.dtb
sda845-4k-panel-mtp-overlay.dtbo-base := sda845.dtb
sda845-4k-panel-cdp-overlay.dtbo-base := sda845.dtb
sda845-4k-panel-qrd-overlay.dtbo-base := sda845.dtb
sda845-v2-cdp-overlay.dtbo-base := sda845-v2.dtb
sda845-v2-mtp-overlay.dtbo-base := sda845-v2.dtb
sda845-v2-qrd-overlay.dtbo-base := sda845-v2.dtb
sda845-v2-hdk-overlay.dtbo-base := sda845-v2.dtb
sda845-v2-svr-overlay.dtbo-base := sda845-v2.dtb
sda845-v2-4k-panel-mtp-overlay.dtbo-base := sda845-v2.dtb
sda845-v2-4k-panel-cdp-overlay.dtbo-base := sda845-v2.dtb
sda845-v2-4k-panel-qrd-overlay.dtbo-base := sda845-v2.dtb
sda845-v2.1-cdp-overlay.dtbo-base := sda845-v2.1.dtb
sda845-v2.1-mtp-overlay.dtbo-base := sda845-v2.1.dtb
sda845-v2.1-qrd-overlay.dtbo-base := sda845-v2.1.dtb
sda845-v2.1-svr-overlay.dtbo-base := sda845-v2.1.dtb
sda845-v2.1-4k-panel-cdp-overlay.dtbo-base := sda845-v2.1.dtb
sda845-v2.1-4k-panel-mtp-overlay.dtbo-base := sda845-v2.1.dtb
sda845-v2.1-4k-panel-qrd-overlay.dtbo-base := sda845-v2.1.dtb
sda845-v2.1-cdp-sdxpoorwills-overlay.dtbo-base := sda845-v2.1.dtb
sda845-v2.1-mtp-sdxpoorwills-overlay.dtbo-base := sda845-v2.1.dtb
sda845-v2-mtp-sdxpoorwills-overlay.dtbo-base := sda845-v2.dtb
else
dtb-$(CONFIG_ARCH_QCOM)	+= apq8016-sbc.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= apq8096-db820c.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= ipq8074-hk01.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8916-mtp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8992-bullhead-rev-101.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8994-angler-rev-101.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8996-mtp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= sdm845-mtp.dtb
endif

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files    := *.dtb *.dtbo
